//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cadru.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cadru.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine the install root path for the .NET Framework..
        /// </summary>
        internal static string ApplicationExcpetion_UnableToDetermineInstallRoot {
            get {
                return ResourceManager.GetString("ApplicationExcpetion_UnableToDetermineInstallRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal enum value: {0}..
        /// </summary>
        internal static string Argument_EnumIllegalVal {
            get {
                return ResourceManager.GetString("Argument_EnumIllegalVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not valid for this usage of the type {1}..
        /// </summary>
        internal static string Argument_InvalidEnumValue {
            get {
                return ResourceManager.GetString("Argument_InvalidEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of flags is invalid..
        /// </summary>
        internal static string Argument_InvalidFlag {
            get {
                return ResourceManager.GetString("Argument_InvalidFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The starting index and ending index refer to the same location in the string..
        /// </summary>
        internal static string Argument_InvalidIndexValuesString {
            get {
                return ResourceManager.GetString("Argument_InvalidIndexValuesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be an Attribute or derived from an Attribute..
        /// </summary>
        internal static string Argument_MustBeAttribute {
            get {
                return ResourceManager.GetString("Argument_MustBeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object must be of type DateTime..
        /// </summary>
        internal static string Argument_MustBeDateTime {
            get {
                return ResourceManager.GetString("Argument_MustBeDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be an IsoDateTime..
        /// </summary>
        internal static string Argument_MustBeIsoDateTime {
            get {
                return ResourceManager.GetString("Argument_MustBeIsoDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object must be of type String..
        /// </summary>
        internal static string Argument_MustBeString {
            get {
                return ResourceManager.GetString("Argument_MustBeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument passed in is not serializable..
        /// </summary>
        internal static string Argument_NotSerializable {
            get {
                return ResourceManager.GetString("Argument_NotSerializable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The starting index refers to a location in the string that is after the ending index..
        /// </summary>
        internal static string Argument_StartIndexGreaterThanEndIndexString {
            get {
                return ResourceManager.GetString("Argument_StartIndexGreaterThanEndIndexString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String cannot be of zero length..
        /// </summary>
        internal static string Argument_StringZeroLength {
            get {
                return ResourceManager.GetString("Argument_StringZeroLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type provided must be an Enum..
        /// </summary>
        internal static string ArgumentExceptionMustBeEnum {
            get {
                return ResourceManager.GetString("ArgumentExceptionMustBeEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String reference not set to an instance of a String..
        /// </summary>
        internal static string ArgumentNull_String {
            get {
                return ResourceManager.GetString("ArgumentNull_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index must be less than the length of string..
        /// </summary>
        internal static string ArgumentOutOfRange_IndexLessThanLength {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_IndexLessThanLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index must be non-negative..
        /// </summary>
        internal static string ArgumentOutOfRange_IndexLessThanZero {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_IndexLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index was out of range. Must be non-negative and less than the length of the string..
        /// </summary>
        internal static string ArgumentOutOfRange_IndexString {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_IndexString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid values are between {0} and {1}, inclusive..
        /// </summary>
        internal static string ArgumentOutOfRange_Range {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not download {0} - FTP server closed the connection..
        /// </summary>
        internal static string DownloadInfoConnectionClosed {
            get {
                return ResourceManager.GetString("DownloadInfoConnectionClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not download {0} - a web page was returned from the web server..
        /// </summary>
        internal static string DownloadInfoInvalidResponseReceived {
            get {
                return ResourceManager.GetString("DownloadInfoInvalidResponseReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download was cancelled..
        /// </summary>
        internal static string FileDownloaderCancelled {
            get {
                return ResourceManager.GetString("FileDownloaderCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading file to {0}..
        /// </summary>
        internal static string FileDownloaderDownloadLocation {
            get {
                return ResourceManager.GetString("FileDownloaderDownloadLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine the order of year, month, and date from &apos;{0}&apos;..
        /// </summary>
        internal static string Format_BadDatePattern {
            get {
                return ResourceManager.GetString("Format_BadDatePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String was not recognized as a valid DateTime..
        /// </summary>
        internal static string Format_BadDateTime {
            get {
                return ResourceManager.GetString("Format_BadDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DateTime represented by the string is not supported in calendar {0}..
        /// </summary>
        internal static string Format_BadDateTimeCalendar {
            get {
                return ResourceManager.GetString("Format_BadDateTimeCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String was not recognized as a valid DateTime because the day of week was incorrect..
        /// </summary>
        internal static string Format_BadDayOfWeek {
            get {
                return ResourceManager.GetString("Format_BadDayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format specifier was invalid..
        /// </summary>
        internal static string Format_BadFormatSpecifier {
            get {
                return ResourceManager.GetString("Format_BadFormatSpecifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a matching quote character for the character &apos;{0}&apos;..
        /// </summary>
        internal static string Format_BadQuote {
            get {
                return ResourceManager.GetString("Format_BadQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DateTime represented by the string is out of range..
        /// </summary>
        internal static string Format_DateOutOfRange {
            get {
                return ResourceManager.GetString("Format_DateOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid IP address was specified..
        /// </summary>
        internal static string Format_Dns_Bad_Ip_Address {
            get {
                return ResourceManager.GetString("Format_Dns_Bad_Ip_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input string was either empty or contained only white space..
        /// </summary>
        internal static string Format_EmptyInputString {
            get {
                return ResourceManager.GetString("Format_EmptyInputString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional non-parsable characters are at the end of the string..
        /// </summary>
        internal static string Format_ExtraJunkAtEnd {
            get {
                return ResourceManager.GetString("Format_ExtraJunkAtEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String was not of correct length..
        /// </summary>
        internal static string Format_InvalidLen {
            get {
                return ResourceManager.GetString("Format_InvalidLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input string was not in a correct format..
        /// </summary>
        internal static string Format_InvalidString {
            get {
                return ResourceManager.GetString("Format_InvalidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String must be exactly one character long..
        /// </summary>
        internal static string Format_NeedSingleChar {
            get {
                return ResourceManager.GetString("Format_NeedSingleChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime pattern &apos;{0}&apos; appears more than once with different values..
        /// </summary>
        internal static string Format_RepeatDateTimePattern {
            get {
                return ResourceManager.GetString("Format_RepeatDateTimePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The String being parsed cannot contain two TimeZone specifiers..
        /// </summary>
        internal static string Format_TwoTimeZoneSpecifiers {
            get {
                return ResourceManager.GetString("Format_TwoTimeZoneSpecifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string was not recognized as a valid DateTime. There is a unknown word starting at index {0}..
        /// </summary>
        internal static string Format_UnknowDateTimeWord {
            get {
                return ResourceManager.GetString("Format_UnknowDateTimeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid cast from &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string InvalidCast_FromTo {
            get {
                return ResourceManager.GetString("InvalidCast_FromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot apply format &quot;{0}&quot; to the date &quot;{1}&quot; as the date is already in local time..
        /// </summary>
        internal static string MDA_InvalidFormatForLocal {
            get {
                return ResourceManager.GetString("MDA_InvalidFormatForLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot apply format &quot;{0}&quot; to the date &quot;{1}&quot; as the date is already in universal time..
        /// </summary>
        internal static string MDA_InvalidFormatForUtc {
            get {
                return ResourceManager.GetString("MDA_InvalidFormatForUtc", resourceCulture);
            }
        }
    }
}
