//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cadru.UnitTest.Framework.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cadru.UnitTest.Framework.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected exception of type {0} but no exception was thrown..
        /// </summary>
        internal static string Assertion_ExceptionNotThrown {
            get {
                return ResourceManager.GetString("Assertion_ExceptionNotThrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected {0} to be assignable from {1}..
        /// </summary>
        internal static string Assertion_ExpectedToBeAssignableFrom {
            get {
                return ResourceManager.GetString("Assertion_ExpectedToBeAssignableFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &amp;lt;{0}&amp;gt; but actual was &amp;lt;{1}&amp;gt;..
        /// </summary>
        internal static string Assertion_GenericFailure {
            get {
                return ResourceManager.GetString("Assertion_GenericFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected type {0} but actual was {1}..
        /// </summary>
        internal static string Assertion_WrongType {
            get {
                return ResourceManager.GetString("Assertion_WrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} failed. {1}.
        /// </summary>
        internal static string AssertionFailed {
            get {
                return ResourceManager.GetString("AssertionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (null).
        /// </summary>
        internal static string Common_NullInMessages {
            get {
                return ResourceManager.GetString("Common_NullInMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String &apos;{0}&apos; contains string &apos;{1}&apos;. {2}..
        /// </summary>
        internal static string DoesNotContainFail {
            get {
                return ResourceManager.GetString("DoesNotContainFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String &apos;{0}&apos; ends with string &apos;{1}&apos;. {2}..
        /// </summary>
        internal static string DoesNotEndWithFail {
            get {
                return ResourceManager.GetString("DoesNotEndWithFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String &apos;{0}&apos; starts with string &apos;{1}&apos;. {2}..
        /// </summary>
        internal static string DoesNotStartWithFail {
            get {
                return ResourceManager.GetString("DoesNotStartWithFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception of type {1} was thrown but was not expected. {0}
        ///Exception Message: {2}
        ///Stack Trace: {3}.
        /// </summary>
        internal static string DoesNotThrowExceptionFailMsg {
            get {
                return ResourceManager.GetString("DoesNotThrowExceptionFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected an empty collection..
        /// </summary>
        internal static string IsCollectionEmptyFailMsg {
            get {
                return ResourceManager.GetString("IsCollectionEmptyFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a collection with 1 or more elements..
        /// </summary>
        internal static string IsCollectionNotEmptyFailMsg {
            get {
                return ResourceManager.GetString("IsCollectionNotEmptyFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected an empty string but actual string had {0} characters..
        /// </summary>
        internal static string IsEmptyStringFailMsg {
            get {
                return ResourceManager.GetString("IsEmptyStringFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected an empty string but actual string was (null)..
        /// </summary>
        internal static string IsEmptyStringFailOnNullMsg {
            get {
                return ResourceManager.GetString("IsEmptyStringFailOnNullMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected {0} to be greater than {1}..
        /// </summary>
        internal static string IsGreaterFailMsg {
            get {
                return ResourceManager.GetString("IsGreaterFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected {0} to be greater than or equal to {1}..
        /// </summary>
        internal static string IsGreaterOrEqualFailMsg {
            get {
                return ResourceManager.GetString("IsGreaterOrEqualFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected {0} to be less than {1}..
        /// </summary>
        internal static string IsLessFailMsg {
            get {
                return ResourceManager.GetString("IsLessFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected {0} to be less than or equal to {1}..
        /// </summary>
        internal static string IsLessOrEqualFailMsg {
            get {
                return ResourceManager.GetString("IsLessOrEqualFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a string with 1 or more characters but actual was empty..
        /// </summary>
        internal static string IsNotEmptyStringFailMsg {
            get {
                return ResourceManager.GetString("IsNotEmptyStringFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a string with 1 or more characters but actual was (null)..
        /// </summary>
        internal static string IsNotEmptyStringFailOnNullMsg {
            get {
                return ResourceManager.GetString("IsNotEmptyStringFailOnNullMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected an ordered collection..
        /// </summary>
        internal static string IsOrderedFail {
            get {
                return ResourceManager.GetString("IsOrderedFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; is invalid. The value cannot be null. {1}..
        /// </summary>
        internal static string NullParameterToAssert {
            get {
                return ResourceManager.GetString("NullParameterToAssert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threw exception {0}, but exception {1} was expected.
        ///Exception Message: {3}
        ///Stack Trace: {4}.
        /// </summary>
        internal static string WrongExceptionThrown {
            get {
                return ResourceManager.GetString("WrongExceptionThrown", resourceCulture);
            }
        }
    }
}
