//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cadru.Json.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cadru.Json.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The character set provided in ContentType is invalid..
        /// </summary>
        internal static string CharSetInvalid {
            get {
                return ResourceManager.GetString("CharSetInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error converting value {0} to a Boolean value..
        /// </summary>
        internal static string JsonConverter_BooleanEnabled_ConversionFailure {
            get {
                return ResourceManager.GetString("JsonConverter.BooleanEnabled.ConversionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing IP address string: {0}.
        /// </summary>
        internal static string JsonConverter_IPAddress_ParseError {
            get {
                return ResourceManager.GetString("JsonConverter.IPAddress.ParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected token or value when parsing IP address. Token: {0}, Value: {1}.
        /// </summary>
        internal static string JsonConverter_IPAddress_UnexpectedToken {
            get {
                return ResourceManager.GetString("JsonConverter.IPAddress.UnexpectedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert date value that is before Unix epoch of 00:00:00 UTC on 1 January 1970..
        /// </summary>
        internal static string JsonConverter_UnixDateTimeConverter_ConversionFailure {
            get {
                return ResourceManager.GetString("JsonConverter.UnixDateTimeConverter.ConversionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing the date value..
        /// </summary>
        internal static string JsonConverter_UnixDateTimeConverter_ParseError {
            get {
                return ResourceManager.GetString("JsonConverter.UnixDateTimeConverter.ParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified type {0} must derive from the specific value&apos;s type {1}..
        /// </summary>
        internal static string SerializeWrongType {
            get {
                return ResourceManager.GetString("SerializeWrongType", resourceCulture);
            }
        }
    }
}
