//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cadru.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cadru.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine the install root path for the .NET Framework..
        /// </summary>
        internal static string ApplicationExcpetion_UnableToDetermineInstallRoot {
            get {
                return ResourceManager.GetString("ApplicationExcpetion_UnableToDetermineInstallRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambiguous match found..
        /// </summary>
        internal static string Arg_AmbiguousMatchException {
            get {
                return ResourceManager.GetString("Arg_AmbiguousMatchException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte array for GUID must be exactly {0} bytes long..
        /// </summary>
        internal static string Arg_GuidArrayCtor {
            get {
                return ResourceManager.GetString("Arg_GuidArrayCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object must be of type ConstrainedNumeric&lt;T&gt;..
        /// </summary>
        internal static string Arg_MustBeConstrainedNumeric {
            get {
                return ResourceManager.GetString("Arg_MustBeConstrainedNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object must be of type SequentialGuid..
        /// </summary>
        internal static string Arg_MustBeSequentialGuid {
            get {
                return ResourceManager.GetString("Arg_MustBeSequentialGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object must be of type UnixTimestamp..
        /// </summary>
        internal static string Arg_MustBeUnixTimestamp {
            get {
                return ResourceManager.GetString("Arg_MustBeUnixTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combination of arguments to the UnixTimestamp constructor is out of the legal range..
        /// </summary>
        internal static string Arg_UnixTimestampRange {
            get {
                return ResourceManager.GetString("Arg_UnixTimestampRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal enum value: {0}..
        /// </summary>
        internal static string Argument_EnumIllegalVal {
            get {
                return ResourceManager.GetString("Argument_EnumIllegalVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not valid for this usage of the type {1}..
        /// </summary>
        internal static string Argument_InvalidEnumValue {
            get {
                return ResourceManager.GetString("Argument_InvalidEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of flags is invalid..
        /// </summary>
        internal static string Argument_InvalidFlag {
            get {
                return ResourceManager.GetString("Argument_InvalidFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The starting index and ending index refer to the same location in the string..
        /// </summary>
        internal static string Argument_InvalidIndexValuesString {
            get {
                return ResourceManager.GetString("Argument_InvalidIndexValuesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be greater than {1}..
        /// </summary>
        internal static string Argument_MinMaxValue {
            get {
                return ResourceManager.GetString("Argument_MinMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be an Attribute or derived from an Attribute..
        /// </summary>
        internal static string Argument_MustBeAttribute {
            get {
                return ResourceManager.GetString("Argument_MustBeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object must be of type DateTime..
        /// </summary>
        internal static string Argument_MustBeDateTime {
            get {
                return ResourceManager.GetString("Argument_MustBeDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be an IsoDateTime..
        /// </summary>
        internal static string Argument_MustBeIsoDateTime {
            get {
                return ResourceManager.GetString("Argument_MustBeIsoDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object must be of type String..
        /// </summary>
        internal static string Argument_MustBeString {
            get {
                return ResourceManager.GetString("Argument_MustBeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument passed in is not serializable..
        /// </summary>
        internal static string Argument_NotSerializable {
            get {
                return ResourceManager.GetString("Argument_NotSerializable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot contain a null (Nothing in Visual Basic) element..
        /// </summary>
        internal static string Argument_NullElement {
            get {
                return ResourceManager.GetString("Argument_NullElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The starting index refers to a location that is after the ending index..
        /// </summary>
        internal static string Argument_StartIndexGreaterThanEndIndex {
            get {
                return ResourceManager.GetString("Argument_StartIndexGreaterThanEndIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The starting index refers to a location in the string that is after the ending index..
        /// </summary>
        internal static string Argument_StartIndexGreaterThanEndIndexString {
            get {
                return ResourceManager.GetString("Argument_StartIndexGreaterThanEndIndexString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String cannot be of zero length..
        /// </summary>
        internal static string Argument_StringZeroLength {
            get {
                return ResourceManager.GetString("Argument_StringZeroLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied UnixTimestamp represents an invalid time.  For example, when the clock is adjusted forward, any time in the period that is skipped is invalid..
        /// </summary>
        internal static string Argument_UnixTimestampIsInvalid {
            get {
                return ResourceManager.GetString("Argument_UnixTimestampIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be an empty string..
        /// </summary>
        internal static string ArgumentException_EmptyString {
            get {
                return ResourceManager.GetString("ArgumentException_EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type provided must be an Enum..
        /// </summary>
        internal static string ArgumentExceptionMustBeEnum {
            get {
                return ResourceManager.GetString("ArgumentExceptionMustBeEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String reference not set to an instance of a String..
        /// </summary>
        internal static string ArgumentNull_String {
            get {
                return ResourceManager.GetString("ArgumentNull_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The added or subtracted value results in an un-representable DateTime..
        /// </summary>
        internal static string ArgumentOutOfRange_DateArithmetic {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_DateArithmetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticks must be between DateTime.MinValue.Ticks and DateTime.MaxValue.Ticks..
        /// </summary>
        internal static string ArgumentOutOfRange_DateTimeBadTicks {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_DateTimeBadTicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day must be between 1 and {0} for month {1}..
        /// </summary>
        internal static string ArgumentOutOfRange_Day {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DayOfWeek enumeration must be in the range 0 through 6..
        /// </summary>
        internal static string ArgumentOutOfRange_DayOfWeek {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_DayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index must be less than the length of string..
        /// </summary>
        internal static string ArgumentOutOfRange_IndexLessThanLength {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_IndexLessThanLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index must be non-negative..
        /// </summary>
        internal static string ArgumentOutOfRange_IndexLessThanZero {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_IndexLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index was out of range. Must be non-negative and less than the length of the string..
        /// </summary>
        internal static string ArgumentOutOfRange_IndexString {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_IndexString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid values are between {0} and {1}..
        /// </summary>
        internal static string ArgumentOutOfRange_Range {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid values are between {0} and {1}, inclusive..
        /// </summary>
        internal static string ArgumentOutOfRange_RangeInclusive {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_RangeInclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months value must be between +/-120000..
        /// </summary>
        internal static string ArgumentOutOfRange_UnixTimestampBadMonths {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_UnixTimestampBadMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds must be between UnixTimestamp.MinValue.Seconds and UnixTimestamp.MaxValue.Seconds..
        /// </summary>
        internal static string ArgumentOutOfRange_UnixTimestampBadSeconds {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_UnixTimestampBadSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years value must be between +/-10000..
        /// </summary>
        internal static string ArgumentOutOfRange_UnixTimestampBadYears {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_UnixTimestampBadYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The upper bound must be greater than the lower bound ..
        /// </summary>
        internal static string ArgumentOutOfRange_UpperBound {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_UpperBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a collection containing &lt;0&gt; items but actual was &lt;{0}&gt; items..
        /// </summary>
        internal static string Assertion_CollectionFailure {
            get {
                return ResourceManager.GetString("Assertion_CollectionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &lt;{0}&gt; but actual was &lt;{1}&gt;..
        /// </summary>
        internal static string Assertion_GenericFailure {
            get {
                return ResourceManager.GetString("Assertion_GenericFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assumption failed..
        /// </summary>
        internal static string AssumptionException_EmptyMessage {
            get {
                return ResourceManager.GetString("AssumptionException_EmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assumption failed. {0}.
        /// </summary>
        internal static string AssumptionException_Message {
            get {
                return ResourceManager.GetString("AssumptionException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not download {0} - FTP server closed the connection..
        /// </summary>
        internal static string DownloadInfoConnectionClosed {
            get {
                return ResourceManager.GetString("DownloadInfoConnectionClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not download {0} - a web page was returned from the web server..
        /// </summary>
        internal static string DownloadInfoInvalidResponseReceived {
            get {
                return ResourceManager.GetString("DownloadInfoInvalidResponseReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download was cancelled..
        /// </summary>
        internal static string FileDownloaderCancelled {
            get {
                return ResourceManager.GetString("FileDownloaderCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading file to {0}..
        /// </summary>
        internal static string FileDownloaderDownloadLocation {
            get {
                return ResourceManager.GetString("FileDownloaderDownloadLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine the order of year, month, and date from &apos;{0}&apos;..
        /// </summary>
        internal static string Format_BadDatePattern {
            get {
                return ResourceManager.GetString("Format_BadDatePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String was not recognized as a valid DateTime..
        /// </summary>
        internal static string Format_BadDateTime {
            get {
                return ResourceManager.GetString("Format_BadDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DateTime represented by the string is not supported in calendar {0}..
        /// </summary>
        internal static string Format_BadDateTimeCalendar {
            get {
                return ResourceManager.GetString("Format_BadDateTimeCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String was not recognized as a valid DateTime because the day of week was incorrect..
        /// </summary>
        internal static string Format_BadDayOfWeek {
            get {
                return ResourceManager.GetString("Format_BadDayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format specifier was invalid..
        /// </summary>
        internal static string Format_BadFormatSpecifier {
            get {
                return ResourceManager.GetString("Format_BadFormatSpecifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a matching quote character for the character &apos;{0}&apos;..
        /// </summary>
        internal static string Format_BadQuote {
            get {
                return ResourceManager.GetString("Format_BadQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DateTime represented by the string is out of range..
        /// </summary>
        internal static string Format_DateOutOfRange {
            get {
                return ResourceManager.GetString("Format_DateOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid IP address was specified..
        /// </summary>
        internal static string Format_Dns_Bad_Ip_Address {
            get {
                return ResourceManager.GetString("Format_Dns_Bad_Ip_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input string was either empty or contained only white space..
        /// </summary>
        internal static string Format_EmptyInputString {
            get {
                return ResourceManager.GetString("Format_EmptyInputString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional non-parsable characters are at the end of the string..
        /// </summary>
        internal static string Format_ExtraJunkAtEnd {
            get {
                return ResourceManager.GetString("Format_ExtraJunkAtEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected {0xdddddddd, etc}..
        /// </summary>
        internal static string Format_GuidBrace {
            get {
                return ResourceManager.GetString("Format_GuidBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a brace, or the length between the previous token and the brace was zero (i.e., &apos;0x,&apos;etc.)..
        /// </summary>
        internal static string Format_GuidBraceAfterLastNumber {
            get {
                return ResourceManager.GetString("Format_GuidBraceAfterLastNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a comma, or the length between the previous token and the comma was zero (i.e., &apos;0x,&apos;etc.)..
        /// </summary>
        internal static string Format_GuidComma {
            get {
                return ResourceManager.GetString("Format_GuidComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashes are in the wrong position for GUID parsing..
        /// </summary>
        internal static string Format_GuidDashes {
            get {
                return ResourceManager.GetString("Format_GuidDashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the ending brace..
        /// </summary>
        internal static string Format_GuidEndBrace {
            get {
                return ResourceManager.GetString("Format_GuidEndBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected hex 0x in &apos;{0}&apos;..
        /// </summary>
        internal static string Format_GuidHexPrefix {
            get {
                return ResourceManager.GetString("Format_GuidHexPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid string should only contain hexadecimal characters..
        /// </summary>
        internal static string Format_GuidInvalidChar {
            get {
                return ResourceManager.GetString("Format_GuidInvalidChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)..
        /// </summary>
        internal static string Format_GuidInvLen {
            get {
                return ResourceManager.GetString("Format_GuidInvLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized Guid format..
        /// </summary>
        internal static string Format_GuidUnrecognized {
            get {
                return ResourceManager.GetString("Format_GuidUnrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format String can be only &quot;D&quot;, &quot;d&quot;, &quot;N&quot;, &quot;n&quot;, &quot;P&quot;, &quot;p&quot;, &quot;B&quot;, &quot;b&quot;, &quot;X&quot; or &quot;x&quot;..
        /// </summary>
        internal static string Format_InvalidGuidFormatSpecification {
            get {
                return ResourceManager.GetString("Format_InvalidGuidFormatSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String was not of correct length..
        /// </summary>
        internal static string Format_InvalidLen {
            get {
                return ResourceManager.GetString("Format_InvalidLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input string was not in a correct format..
        /// </summary>
        internal static string Format_InvalidString {
            get {
                return ResourceManager.GetString("Format_InvalidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String must be exactly one character long..
        /// </summary>
        internal static string Format_NeedSingleChar {
            get {
                return ResourceManager.GetString("Format_NeedSingleChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime pattern &apos;{0}&apos; appears more than once with different values..
        /// </summary>
        internal static string Format_RepeatDateTimePattern {
            get {
                return ResourceManager.GetString("Format_RepeatDateTimePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The String being parsed cannot contain two TimeZone specifiers..
        /// </summary>
        internal static string Format_TwoTimeZoneSpecifiers {
            get {
                return ResourceManager.GetString("Format_TwoTimeZoneSpecifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string was not recognized as a valid DateTime. There is a unknown word starting at index {0}..
        /// </summary>
        internal static string Format_UnknowDateTimeWord {
            get {
                return ResourceManager.GetString("Format_UnknowDateTimeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to convert the given value to a color..
        /// </summary>
        internal static string InvalidCast_Color {
            get {
                return ResourceManager.GetString("InvalidCast.Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid cast from &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string InvalidCast_FromTo {
            get {
                return ResourceManager.GetString("InvalidCast_FromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve property &quot;{0}&quot; because localization failed.  Type &quot;{1}&quot; is not public or does not contain a public static string property with the name &quot;{2}&quot;..
        /// </summary>
        internal static string InvalidOperation_LocalizationFailed {
            get {
                return ResourceManager.GetString("InvalidOperation_LocalizationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot apply format &quot;{0}&quot; to the date &quot;{1}&quot; as the date is already in local time..
        /// </summary>
        internal static string MDA_InvalidFormatForLocal {
            get {
                return ResourceManager.GetString("MDA_InvalidFormatForLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot apply format &quot;{0}&quot; to the date &quot;{1}&quot; as the date is already in universal time..
        /// </summary>
        internal static string MDA_InvalidFormatForUtc {
            get {
                return ResourceManager.GetString("MDA_InvalidFormatForUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        internal static string RelativeDateFormatStringDaysAgo {
            get {
                return ResourceManager.GetString("RelativeDateFormatStringDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days from now.
        /// </summary>
        internal static string RelativeDateFormatStringDaysFromNow {
            get {
                return ResourceManager.GetString("RelativeDateFormatStringDaysFromNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:MMM d, yyyy}.
        /// </summary>
        internal static string RelativeDateFormatStringDefault {
            get {
                return ResourceManager.GetString("RelativeDateFormatStringDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today, {0:h&apos;:&apos;mm&apos; &apos;tt}.
        /// </summary>
        internal static string RelativeDateFormatStringToday {
            get {
                return ResourceManager.GetString("RelativeDateFormatStringToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        internal static string RelativeDateFormatStringTomorrow {
            get {
                return ResourceManager.GetString("RelativeDateFormatStringTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        internal static string RelativeDateFormatStringYesterday {
            get {
                return ResourceManager.GetString("RelativeDateFormatStringYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        internal static string RelativeTimeFormatStringDay {
            get {
                return ResourceManager.GetString("RelativeTimeFormatStringDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string RelativeTimeFormatStringDays {
            get {
                return ResourceManager.GetString("RelativeTimeFormatStringDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} from now.
        /// </summary>
        internal static string RelativeTimeFormatStringFuture {
            get {
                return ResourceManager.GetString("RelativeTimeFormatStringFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        internal static string RelativeTimeFormatStringHour {
            get {
                return ResourceManager.GetString("RelativeTimeFormatStringHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string RelativeTimeFormatStringHours {
            get {
                return ResourceManager.GetString("RelativeTimeFormatStringHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        internal static string RelativeTimeFormatStringMinute {
            get {
                return ResourceManager.GetString("RelativeTimeFormatStringMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string RelativeTimeFormatStringMinutes {
            get {
                return ResourceManager.GetString("RelativeTimeFormatStringMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        internal static string RelativeTimeFormatStringMonth {
            get {
                return ResourceManager.GetString("RelativeTimeFormatStringMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        internal static string RelativeTimeFormatStringMonths {
            get {
                return ResourceManager.GetString("RelativeTimeFormatStringMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} ago.
        /// </summary>
        internal static string RelativeTimeFormatStringPast {
            get {
                return ResourceManager.GetString("RelativeTimeFormatStringPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        internal static string RelativeTimeFormatStringSecond {
            get {
                return ResourceManager.GetString("RelativeTimeFormatStringSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string RelativeTimeFormatStringSeconds {
            get {
                return ResourceManager.GetString("RelativeTimeFormatStringSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        internal static string RelativeTimeFormatStringYear {
            get {
                return ResourceManager.GetString("RelativeTimeFormatStringYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        internal static string RelativeTimeFormatStringYears {
            get {
                return ResourceManager.GetString("RelativeTimeFormatStringYears", resourceCulture);
            }
        }
    }
}
